// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akhtqntsgeggaoqkuqpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFraHRxbnRzZ2VnZ2FvcWt1cXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODY0MDQsImV4cCI6MjA3Mzk2MjQwNH0.pOUC28_oydvZJcM52ly2C3_PbWfuQoY2Q9xLgExdzMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});